### ISSUE TITLE
can't install in windows

### ISSUE THREAD

**Issue by robertIsaac** [borremosch/cobertura-merge#40]
in windows it try for some reason to locate python package then fail
full error
```
yarn install cobertura-merge    
yarn install v1.22.19
error `install` has been replaced with `add` to add new dependencies. Run "yarn add cobertura-merge" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS C:\Users\aa.risaac\repos\Dashboard> yarn add cobertura-merge -D 
yarn add v1.22.19
[1/4] Resolving packages...
warning cobertura-merge > xml2json > joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and securi
ty patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning cobertura-merge > xml2json > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and securi
ty patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning cobertura-merge > xml2json > joi > hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and 
security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning cobertura-merge > xml2json > joi > topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning cobertura-merge > xml2json > joi > topo > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security iss
ues.
[2/4] Fetching packages...
warning Pattern ["object-assign@latest"] is trying to unpack in the same destination "C:\\Users\\aa.risaac\\AppData\\Local\\Yarn\\Cache\\v6\\npm-object-assign-4.1.1-2109adc7965887cfc05cbbd442cac8bfbb360863-integrity\\node_module
s\\object-assign" as pattern ["object-assign@^4","object-assign@^4.0.1","object-assign@^4.1.1","object-assign@^4.1.1"]. This could result in non-deterministic behavior, skipping.
[3/4] Linking dependencies...
warning " > ngx-device-detector@3.0.0" has incorrect peer dependency "@angular/common@>=7.0.0 <=13.0.0 || ^13.0.0".
warning " > ngx-device-detector@3.0.0" has incorrect peer dependency "@angular/core@>=7.0.0 <=13.0.0 || ^13.0.0".
warning "@angular-devkit/build-angular > source-map-loader@4.0.1" has incorrect peer dependency "webpack@^5.72.1".
warning " > @angular-eslint/schematics@13.1.0" has incorrect peer dependency "@angular/cli@>= 13.0.0 < 14.0.0".
warning " > @cypress/webpack-preprocessor@5.11.1" has unmet peer dependency "@babel/core@^7.0.1".
warning " > @cypress/webpack-preprocessor@5.11.1" has unmet peer dependency "@babel/preset-env@^7.0.0".
warning " > @cypress/webpack-preprocessor@5.11.1" has unmet peer dependency "babel-loader@^8.0.2".
warning " > cypress-multi-reporters@1.5.0" has unmet peer dependency "mocha@>=3.1.2".
warning " > mochawesome@7.0.1" has unmet peer dependency "mocha@>=7".
[4/4] Building fresh packages...
error C:\Users\aa.risaac\repos\Dashboard\node_modules\node-expat: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\aa.risaac\repos\Dashboard\node_modules\node-expat
Output:
C:\Users\aa.risaac\repos\Dashboard\node_modules\node-expat>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "
" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.16.0 | win32 | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Users\aa.risaac\AppData\Local\Programs\Python\Python39\python.exe
gyp ERR! find Python - "C:\Users\aa.risaac\AppData\Local\Programs\Python\Python39\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe
gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\aa.risaac\AppData\Local\Programs\Python\Python39-32\python.exe
gyp ERR! find Python - "C:\Users\aa.risaac\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe
gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\aa.risaac\AppData\Local\Programs\Python\Python38\python.exe
gyp ERR! find Python - "C:\Users\aa.risaac\AppData\Local\Programs\Python\Python38\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python38\python.exe
gyp ERR! find Python - "C:\Program Files\Python38\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\aa.risaac\AppData\Local\Programs\Python\Python38-32\python.exe
gyp ERR! find Python - "C:\Users\aa.risaac\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python38-32\python.exe
gyp ERR! find Python - "C:\Program Files\Python38-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
gyp ERR! find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\aa.risaac\AppData\Local\Programs\Python\Python37\python.exe
gyp ERR! find Python - "C:\Users\aa.risaac\AppData\Local\Programs\Python\Python37\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python37\python.exe
gyp ERR! find Python - "C:\Program Files\Python37\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\aa.risaac\AppData\Local\Programs\Python\Python37-32\python.exe
gyp ERR! find Python - "C:\Users\aa.risaac\AppData\Local\Programs\Python\Python37-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python37-32\python.exe
gyp ERR! find Python - "C:\Program Files\Python37-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python37-32\python.exe
gyp ERR! find Python - "C:\Program Files (x86)\Python37-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\aa.risaac\AppData\Local\Programs\Python\Python36\python.exe
gyp ERR! find Python - "C:\Users\aa.risaac\AppData\Local\Programs\Python\Python36\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python36\python.exe
gyp ERR! find Python - "C:\Program Files\Python36\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\aa.risaac\AppData\Local\Programs\Python\Python36-32\python.exe
gyp ERR! find Python - "C:\Users\aa.risaac\AppData\Local\Programs\Python\Python36-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python36-32\python.exe
gyp ERR! find Python - "C:\Program Files\Python36-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python36-32\python.exe
gyp ERR! find Python - "C:\Program Files (x86)\Python36-32\python.exe" could not be run
gyp ERR! find Python checking if the py launcher can be used to find Python 3
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Users\aa.risaac\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:330:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Users\aa.risaac\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:159:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\aa.risaac\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:228:18)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\aa.risaac\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:294:16)
gyp ERR! stack     at exithandler (node:child_process:427:5)
gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\aa.risaac\repos\Dashboard\node_modules\node-expat
gyp ERR! node -v v18.16.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by MattiJarvinen** [comment]
You need to read https://github.com/nodejs/node-gyp#on-windows

This is how nodejs handles building native binaries.

**Comment by robertIsaac** [comment]
> You need to read https://github.com/nodejs/node-gyp#on-windows
> 
> This is how nodejs handles building native binaries.

can you publish binary like other libraries usually do so we don't have to

**Comment by jorgealgaba** [comment]
Hi @robertIsaac, you need to install python and have it on your path to fix it :)

**Comment by robertIsaac** [comment]
Works after installing python
