### ISSUE TITLE
Error on Node v20 LTS

### ISSUE THREAD

**Issue by jerkovicl** [borremosch/cobertura-merge#41]
```
Error: The module '\\?\C:\Git\projects\fiyu\frontend\node_modules\node-expat\build\Release\node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at bindings (C:\Git\projects\fiyu\frontend\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Git\projects\fiyu\frontend\node_modules\node-expat\lib\node-expat.js:4:34)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
Error: Command failed: npx cobertura-merge -o merged-cobertura-coverage.xml ui=libs-ui-ct-cobertura-coverage.xml ui=libs-ui-cobertura-coverage.xml ui=apps-ui-e2e-cobertura-coverage.xml showcase=apps-showcase-e2e-cobertura-coverage.xml showcase=apps-showcase-cobertura-coverage.xml
```

```
node --version
v20.10.0
```

@borremosch  can we get support for node v20

**Comment by p18a** [comment]
Running `npm rebuild` fixed this for me

**Comment by jerkovicl** [comment]
@p18a yep i can confirm it works, thx!
